external-api:
  url:
    baseUrl: 'https://sandbox.platfr.io/api/gbs/banking/v4.0/accounts/'
spring:
  datasource:
    url: jdbc:h2:mem:fabrickDB
    username: fabrick
    password: fabrick
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create
  h2:
    console.enabled: true