logging:
  level:
    root: 'INFO'
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
external-api:
  url:
    baseUrl: 'https://sandbox.platfr.io/api/gbs/banking/v4.0/accounts/'
    balance: '/balance'
    transaction: '/transactions'
    moneyTransfer: '/payments/money-transfers'
  apiKey: 'FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP'
  accountId: '14537780'
  keyId: '3202'
  authSchema: 'S2S'
  timeZone:
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/fabrickDB?createDatabaseIfNotExist=true
    username: root
    password: fabrick
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false